export const contactsModel = {
    RESULTS: "results",
    NAME: "name",
    NAME_FIRST: "first",
    NAME_LAST: "last",
    LOCATION: "location",
    LOCATION_STREET: "street",
    STREET_NUMBER: "number",
    STREET_NAME: "name",
    LOCATION_CITY: "city",
    LOCATION_POSTCODE: "postcode",
    LOCATION_STATE: "state",
    EMAIL: "email",
    LOGIN: "login",
    LOGIN_USERNAME: "username",
    PHONE: "phone",
    ID: "id",
    ID_NAME: "name",
    ID_VALUE: "value",
    PICTURE: "picture",
    PICTURE_LARGE: "large",
    PICTURE_MEDIUM: "medium",
    PICTURE_THUMBNAIL: "thumbnail"
};